#!/bin/bash

# trayer
trayer --edge top --align right --width 20 --height 26 --transparent true --tint 0x6D6D6D &

# Set the background color
xsetroot -solid midnightblue

# Fire up apps
xscreensaver -no-splash &
 
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

if [ -x /usr/bin/gmixer ] ; then
   gmixer -d &
fi


exec xmonad
