#!/bin/bash

# configure xrandr for multiple monitors
INTERNAL_OUTPUT="LVDS1"
EXTERNAL_OUTPUT="VGA1"
# 
EXTERNAL_LOCATION=""

# In case I want to have both monitors on
case "$EXTERNAL_LOCATION" in
    left|LEFT)
        EXTERNAL_LOCATION="--left-of $INTERNAL_OUTPUT"
        ;;
    right|RIGHT)
        EXTERNAL_LOCATION="--right-of $INTERNAL_OUTPUT"
        ;;
    top|TOP|above|ABOVE)
        EXTERNAL_LOCATION="--above $INTERNAL_OUTPUT"
        ;;
    bottom|BOTTOM|below|BELOW)
        EXTERNAL_LOCATION="--below $INTERNAL_OUTPUT"
        ;;
    *)
        EXTERNAL_LOCATION="--left-of $INTERNAL_OUTPUT"
        ;;
esac
xrandr | grep $EXTERNAL_OUTPUT | grep " connected "

if [ $? -eq 0 ]; then
    xrandr --output $INTERNAL_OUTPUT --off --output $EXTERNAL_OUTPUT --auto
    # Alternative command in case of trouble:
    # (sleep 2; xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto $EXTERNAL_LOCATION) &
else
    xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
fi




# trayer
trayer --edge top --align right --width 20 --height 26 --transparent true --tint 0x6D6D6D &

# Set the background color
# xsetroot -solid midnightblue

# Set wallpaper
loadimage -onroot -fillscreen /usr/share/wallpapers/openSUSEdefault/contents/images/1600x1200.jpg

# set mouse cursor
xsetroot -cursor_name left_ptr

# Fire up apps
xscreensaver -no-splash &
 
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

if [ -x /usr/bin/gmixer ] ; then
   gmixer -d &
fi

if [ -x /usr/bin/xfce4-clipman ]; then
    xfce4-clipman &
fi    
    
exec xmonad
